### ISSUE TITLE
All the nodes children are assigned to all parent nodes

### ISSUE THREAD

**Issue by obadrawi** [kyma-project/console#1370]
**Description**
A Luigi configuration with two navigation nodes each having its own child creates a problem when deployed as a MicroFrontend

**Expected result**
each node has its own child and navigation works normally

**Actual result**
both children are added to both parent nodes and the error "Could not map the exact target node for the requested route" appears

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
The following example allows reproducing the bug.
Here,  all children nodes (`/apiview/:id` and `/createapi/:event`  )  end up as children nodes for both parents (`/apiview`, `/createapi/`)
```
navigationNodes:
   - label: {{ .Values.kyma-console.navigation.name }}
     navigationPath: {{ template "bundle.fullname" . }}
     viewUrl: /angular.html
   - label: Api List
     navigationPath: {{ template "bundle.fullname" . }}/apiview
     viewUrl: /angular.html#/apiview
     showInNavigation: false
   - label: Api Local
     navigationPath: {{ template "bundle.fullname" . }}/apiview/:id
     viewUrl: /angular.html#/apiview/:id
     showInNavigation: false
   - label: Api Remote
     navigationPath: {{ template "bundle.fullname" . }}/apiview/:id/:remote
     viewUrl: /angular.html#/apiview/:id/:remote
     showInNavigation: false
    - label: Create Api
      navigationPath: {{ template "bundle.fullname" . }}/createapi
      viewUrl: /angular.html#/createapi
      showInNavigation: false
    - label: Create Event
      navigationPath: {{ template "bundle.fullname" . }}/createapi/:event
      viewUrl: /angular.html#/createapi/:event
      showInNavigation: false
```
