### ISSUE TITLE
Trigger is not displayed when has no port in service view and reports error

### ISSUE THREAD

**Issue by dbadura** [kyma-project/console#2029]
**Description**
When I created such event trigge through kubectl:
```
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: api-mssql-go-trigger
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: app # name of the application/system
      type: order.created # event type
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: api-mssql-go
    uri: /orderCodeEvent
```
The trigger is not visible and I see following error message:
```
Couldn't fetch Event Triggers for Function "api-mssql-go" due to this error: while extracting port: missing port in address
```
**Expected result**
The trigger is displayed correctly and no error is shown.

**Actual result**
The trigger is not visible in console UI and I got error.

**Steps to reproduce**
Apply provided `trigel.yaml`

**Troubleshooting**
![Screen Shot 2020-10-13 at 15 15 02](https://user-images.githubusercontent.com/45110612/95865672-3a8c5500-0d67-11eb-825b-e3cb943f545d.png)
