### ISSUE TITLE
Conditional visibility of "create application" and "connect application"

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#565]
Provide possibility to configure if "create application" and "connect application" should be visible or not

Proposed solution:

in kyma/resources/application-connector/templates/applications-microfrontend.yaml
```
apiVersion: "ui.kyma-project.io/v1alpha1"
kind: ClusterMicroFrontend
metadata:
  name: applicationsmicrofrontend
  labels:
    app:  applicationsmicrofrontend
spec:
  displayName: Applications
  version: v1
  category: Integration
  placement: cluster
  viewBaseUrl: 'https://console.{{ js .Values.global.domainName }}/consoleapp.html#'
  navigationNodes:
    - label: Applications
      navigationPath: apps
      viewUrl: '/home/settings/apps'
      order: 1
      settings:
        readOnly: {{ js .Values.XYZ.applicationManagementDisabled }}
    - label: Application Details
      navigationPath: apps/details
      viewUrl: '/home/settings/apps'
    - label: Application Details
      navigationPath: apps/details/:name
      viewUrl: '/home/settings/apps/:name'
      settings:
        readOnly: {{ js .Values.XYZ.applicationManagementDisabled }}
```
Console should read mf settings and add them to the context object.
