### ISSUE TITLE
"requiredBackendModules" as microfrontend visibility configuration

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#578]
A microfrontend CR should be able to define a list of backendmodules which are required to be present to show the node (i.e. without ALL of them the view will not work).

Example:
```
apiVersion: "ui.kyma-project.io/v1alpha1"
kind: ClusterMicroFrontend
metadata:
  name: david
  labels:
    app: david
spec:
  displayName: Hasselhoff
  version: v1
  category: Fun
  placement: cluster
  viewBaseUrl: 'https://console.{{ js .Values.global.domainName }}/consoleapp.html#'
  navigationNodes:
    - label: Burger
      navigationPath: king
      viewUrl: '/hassle/hoff'
      order: 1
      requiredBackendModules:
        - mod1
        - mod2
```
