### ISSUE TITLE
Console content view is hardcoded to specific groups only

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#753]
**Description**

- we use graphql, so make one POST and not several like in REST
- left nav must be scalable and extendable as described below
- the only mandatory metadata is `title`
- CRD supports multiple markdown types, we should support it in UI, now I see `docs: await this.getAllUrls(docs.assets[0].files)`

**Expected result**

See new group called Dependencies (maybe it is a right time to introduce collapse by default the groups) and after clicking Istio, I can see few markdown files renders and available for read.

**Actual result**

with below example I cannot see Istio on the list of docs, in new group called dependencies
if I change example and set group `components`, Istio appears on the list, but content is not loaded, 1 possible reason -> in UI we are not supporting multiple markdown types, or we are not resilient enough and 2 possible reasons is that we fail as the files has only `title` metadata, but no `type` metadata. Hard to say really what is going on

**Steps to reproduce**

create such crd and it won't work:
```

cat <<EOF | kubectl apply -f -
apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  name: istio-docs
  labels:
    cms.kyma-project.io/view-context: docs-ui
    cms.kyma-project.io/order: "1"
    cms.kyma-project.io/group-name: dependencies
spec:
  displayName: "Istio"
  sources:
   - type: markdown
     name: markdown-files-security
     mode: package
     url: https://github.com/istio/istio.io/archive/master.zip
     filter: content/docs/concepts/security
   - type: markdown
     name: markdown-files-policies
     mode: package
     url: https://github.com/istio/istio.io/archive/master.zip
     filter: content/docs/concepts/policies-and-telemetry
EOF
```

**Troubleshooting**

After checking browser console, looks like we are doing two calls to graphql for clusterdocstopics, 1 for docs for root group, other for components group. This prevents using any kind of groups
